// <auto-generated />
using System;
using CactusDepot.Shared.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CactusDepot.Common.DataContext.Migrations
{
    [DbContext(typeof(SeedsDbContext))]
    partial class SeedsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CactusDepot.Shared.Models.Seeds.CactusSeed", b =>
                {
                    b.Property<int>("SeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Parent1CatalogNum")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Parent2CatalogNum")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SeedAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SeedCatalogNum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SeedCollectedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SeedLastSowedYear")
                        .HasColumnType("int");

                    b.Property<string>("SeedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SeedNote")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SeedRating")
                        .HasColumnType("int");

                    b.Property<int?>("SeedSeedsQty")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("SeedSource")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SeedYear")
                        .HasColumnType("int");

                    b.HasKey("SeedId");

                    b.ToTable("CactusSeeds");
                });
#pragma warning restore 612, 618
        }
    }
}
